const FRONTEND_URL = process.env.NODE_ENV === 'development' ? 'http://localhost:5000' : 'https://classicarmory.org';

const CURRENT_ADDON_VERSION = 1.2;

const gender = {
  1: 'Neutrum / Unknown',
  2: 'Male',
  3: 'Female',
};

const INVENTORY_IDS = {
  1: 'head',
  2: 'neck',
  3: 'shoulder',
  4: 'shirt',
  5: 'chest',
  6: 'waist',
  7: 'legs',
  8: 'feet',
  9: 'wrist',
  10: 'hands',
  11: 'finger 1',
  12: 'finger 2',
  13: 'trinket 1',
  14: 'trinket 2',
  15: 'back',
  16: 'main hand',
  17: 'off hand',
  18: 'ranged',
  19: 'tabard',
};

const CLASSES = {
  1: 'Warrior',
  2: 'Paladin',
  3: 'Hunter',
  4: 'Rogue',
  5: 'Priest',
  6: 'DeathKnight',
  7: 'Shaman',
  8: 'Mage',
  9: 'Warlock',
  10: 'Monk',
  11: 'Druid',
  12: 'Demon',
};

const RACES = {
  1: { name: 'Human', faction: 'Alliance' },
  2: { name: 'Orc', faction: 'Horde' },
  3: { name: 'Dwarf', faction: 'Alliance' },
  4: { name: 'Night Elf', faction: 'Alliance' },
  5: { name: 'Undead', faction: 'Horde' },
  6: { name: 'Tauren', faction: 'Horde' },
  7: { name: 'Gnome', faction: 'Alliance' },
  8: { name: 'Troll', faction: 'Horde' },
};

const ENCHANT_INVENTORY_IDS = {
  1: 'head',
  3: 'shoulder',
  5: 'chest',
  7: 'legs',
  8: 'feet',
  9: 'wrist',
  10: 'hands',
  15: 'back',
  16: 'main hand',
  17: 'off hand',
  18: 'ranged',
};

const ENCHANT_VALUES = {
  29: 1,
  30: 3,
  31: 5,
  32: 7,
  33: 8,
  34: 9,
  35: 10,
  36: 15,
  37: 16,
  38: 17,
  39: 18,
};

const SERVERS = {
  1: { name: 'Ashbringer', type: 'PVP' },
  2: { name: 'Bloodfang', type: 'PVP' },
  3: { name: 'Dragonfang', type: 'PVP' },
  4: { name: 'Dreadmist', type: 'PVP ' },
  5: { name: 'Earthshaker', type: 'PVP' },
  6: { name: 'Firemaw', type: 'PVP' },
  7: { name: 'Flamelash', type: 'PVP' },
  8: { name: 'Gandling', type: 'PVP' },
  9: { name: 'Gehennas', type: 'PVP' },
  10: { name: 'Golemagg', type: 'PVP' },
  11: { name: 'Hydraxian Waterlords', type: 'RP' },
  12: { name: 'Judgement', type: 'PVP' },
  13: { name: 'Mirage Raceway', type: 'Normal' },
  14: { name: 'Mograine', type: 'PVP' },
  15: { name: 'Nethergarde Keep', type: 'Normal' },
  16: { name: 'Noggenfogger', type: 'PVP' },
  17: { name: 'Pyrewood Village', type: 'Normal' },
  18: { name: 'Razorgore', type: 'PVP' },
  19: { name: 'Shazzrah', type: 'PVP' },
  20: { name: 'Skullflame', type: 'PVP' },
  21: { name: 'Stonespine', type: 'PVP' },
  22: { name: 'Ten Storms', type: 'PVP' },
  23: { name: 'Zandalar Tribe', type: 'RPPVP' },
  24: { name: 'Anathema', type: 'PvP' },
  25: { name: 'Arcanite Reaper', type: 'PvP' },
  26: { name: 'Arugal', type: 'PvP' },
  27: { name: 'Ashkandi', type: 'PvE' },
  28: { name: 'Atiesh', type: 'PvE' },
  29: { name: 'Azuresong', type: 'PvE' },
  30: { name: 'Benediction', type: 'PvP' },
  31: { name: 'Bigglesworth', type: 'PvP' },
  32: { name: 'Blaumeux', type: 'PvP' },
  33: { name: 'Bloodsail Buccaneers', type: 'RP' },
  34: { name: 'Deviate Delight', type: 'PvPRP' },
  35: { name: 'Earthfury', type: 'PvP' },
  36: { name: 'Faerlina', type: 'PvP' },
  37: { name: 'Fairbanks', type: 'PvP' },
  38: { name: 'Felstriker', type: 'PvP' },
  39: { name: 'Grobbulus', type: 'PvPRP' },
  40: { name: 'Heartseeker', type: 'PvP' },
  41: { name: 'Herod', type: 'PvP' },
  42: { name: 'Incendius', type: 'PvP' },
  43: { name: 'Kirtonos', type: 'PvP' },
  44: { name: 'Kromcrush', type: 'PvP' },
  45: { name: 'Kurinnaxx', type: 'PvP' },
  46: { name: 'Loatheb', type: 'PvP' },
  47: { name: 'Mankrik', type: 'PvE' },
  48: { name: 'Myzrael', type: 'PvE' },
  49: { name: 'Netherwind', type: 'PvP' },
  50: { name: 'Old Blanchy', type: 'PvE' },
  51: { name: 'Pagle', type: 'PvE' },
  52: { name: 'Rattlegore', type: 'PvP' },
  53: { name: 'Remulos', type: 'PvE' },
  54: { name: 'Skeram', type: 'PvP' },
  55: { name: 'Smolderweb', type: 'PvP' },
  56: { name: 'Stalagg', type: 'PvP' },
  57: { name: "ul'thraze", type: 'PvP' },
  58: { name: 'Sulfuras', type: 'PvP' },
  59: { name: 'Thalnos', type: 'PvP' },
  60: { name: 'Thunderfury', type: 'PvP' },
  61: { name: 'Westfall', type: 'PvE' },
  62: { name: 'Whitemane', type: 'PvP' },
  63: { name: 'Windseeker', type: 'PvE' },
  64: { name: 'Yojamba', type: 'PvP' },
};

const SLOTS = [
  'slot_1',
  'slot_1',
  'slot_2',
  'slot_3',
  'slot_4',
  'slot_5',
  'slot_6',
  'slot_7',
  'slot_8',
  'slot_9',
  'slot_10',
  'slot_11',
  'slot_12',
  'slot_13',
  'slot_14',
  'slot_15',
  'slot_16',
  'slot_17',
  'slot_18',
  'slot_19',
];


const PLAYER_VALUES = {
  0: 'uploader',
  1: 'lastSeen',
  2: 'serverId',
  3: 'name',
  4: 'guild',
  5: 'guildRank',
  6: 'level',
  7: 'classId',
  8: 'raceId',
  9: 'genderId',
};

const GEAR_VALUES = {
  10: 1,
  11: 2,
  12: 3,
  13: 4,
  14: 5,
  15: 6,
  16: 7,
  17: 8,
  18: 9,
  19: 10,
  20: 11,
  21: 12,
  22: 13,
  23: 14,
  24: 15,
  25: 16,
  26: 17,
  27: 18,
  28: 19,
};

const HONOR_VALUES = {
  40: 'todayHK',
  41: 'yesterdayHK',
  42: 'yesterdayHonor',
  43: 'lifetimeHK',
  44: 'honorProgress',
  45: 'rankNumber',
  46: 'thisweekHK',
  47: 'thisweekHonor',
  48: 'lastweekHK',
  49: 'lastweekHonor',
  50: 'lastweekStanding',
  51: 'lifetimeDK',
  52: 'lifetimeRank',
};


const VALID_ROW_LENGTH = Object.keys(GEAR_VALUES).length + Object.keys(HONOR_VALUES).length
+ Object.keys(ENCHANT_VALUES).length + Object.keys(PLAYER_VALUES).length;

module.exports = {
  gender,
  INVENTORY_IDS,
  PLAYER_VALUES,
  GEAR_VALUES,
  ENCHANT_INVENTORY_IDS,
  ENCHANT_VALUES,
  SLOTS,
  HONOR_VALUES,
  RACES,
  FRONTEND_URL,
  CLASSES,
  SERVERS,
  VALID_ROW_LENGTH,
  CURRENT_ADDON_VERSION,
};
